In [ ]:
from nltk import ngrams
sentence = "The weather is warm and sunny today so we went out today. But tomorrow it will rain"
n = 3
unigrams = ngrams(sentence.split(), n)
for grams in unigrams:
  print (grams)


('The', 'weather', 'is')
('weather', 'is', 'warm')
('is', 'warm', 'and')
('warm', 'and', 'sunny')
('and', 'sunny', 'today')
('sunny', 'today', 'so')
('today', 'so', 'we')
('so', 'we', 'went')
('we', 'went', 'out')
('went', 'out', 'today.')
('out', 'today.', 'But')
('today.', 'But', 'tomorrow')
('But', 'tomorrow', 'it')
('tomorrow', 'it', 'will')
('it', 'will', 'rain')


In [ ]:
# prompt: generate proability distribution for next word prediction for ngram of 3

from nltk import ngrams
from collections import defaultdict

sentence = "My address is Tuwaiq Academy.The weather is warm and sunny today so we went out today. But tomorrow it will rain. The weather is colder day after. The weather is so good. The weather is colder before"
n = 3

ngram_counts = defaultdict(lambda: defaultdict(lambda: 0))
total_counts = defaultdict(lambda: 0)

words = sentence.split()
for i in range(len(words) - n + 1):
  ngram = tuple(words[i:i+n-1])
  next_word = words[i+n-1]
  ngram_counts[ngram][next_word] += 1
  total_counts[ngram] += 1

prob_dist = defaultdict(lambda: {})
for ngram, next_word_counts in ngram_counts.items():
  for next_word, count in next_word_counts.items():
    prob_dist[ngram][next_word] = count / total_counts[ngram]

print(prob_dist)


defaultdict(<function <lambda> at 0x7b6e4ab99090>, {('My', 'address'): {'is': 1.0}, ('address', 'is'): {'Tuwaiq': 1.0}, ('is', 'Tuwaiq'): {'Academy.The': 1.0}, ('Tuwaiq', 'Academy.The'): {'weather': 1.0}, ('Academy.The', 'weather'): {'is': 1.0}, ('weather', 'is'): {'warm': 0.25, 'colder': 0.5, 'so': 0.25}, ('is', 'warm'): {'and': 1.0}, ('warm', 'and'): {'sunny': 1.0}, ('and', 'sunny'): {'today': 1.0}, ('sunny', 'today'): {'so': 1.0}, ('today', 'so'): {'we': 1.0}, ('so', 'we'): {'went': 1.0}, ('we', 'went'): {'out': 1.0}, ('went', 'out'): {'today.': 1.0}, ('out', 'today.'): {'But': 1.0}, ('today.', 'But'): {'tomorrow': 1.0}, ('But', 'tomorrow'): {'it': 1.0}, ('tomorrow', 'it'): {'will': 1.0}, ('it', 'will'): {'rain.': 1.0}, ('will', 'rain.'): {'The': 1.0}, ('rain.', 'The'): {'weather': 1.0}, ('The', 'weather'): {'is': 1.0}, ('is', 'colder'): {'day': 0.5, 'before': 0.5}, ('colder', 'day'): {'after.': 1.0}, ('day', 'after.'): {'The': 1.0}, ('after.', 'The'): {'weather': 1.0}, ('is', 'so')

In [ ]:


from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

corpus = [
 'This is the first, document.',
 'This document is the second document.',
 'And this is the third one.',
 'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X.toarray())


['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
X = vectorizer.fit_transform(corpus)
pd.DataFrame(X.A, columns=vectorizer.get_feature_names_out())


and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         2      0   1    0       1    1      0     1
2    1         0      0   1    1       0    1      1     1
3    0         1      1   1    0       0    1      0     1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
"Tune a hyperparameter.",
"You can tune a piano but you can't tune a fish.",
           "Fish who eat fish, catch fish.",
"People can tune a fish or a hyperparameter.",
           "It is hard to catch fish and tune it.",]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(np.round(X.A,3),columns=vectorizer.get_feature_names_out())
df


catch    eat   fish   hard  hyperparameter  people  piano   tune
0  0.000  0.000  0.000  0.000           0.820   0.000  0.000  0.573
1  0.000  0.000  0.350  0.000           0.000   0.000  0.622  0.701
2  0.380  0.471  0.796  0.000           0.000   0.000  0.000  0.000
3  0.000  0.000  0.373  0.000           0.534   0.661  0.000  0.373
4  0.534  0.000  0.373  0.661           0.000   0.000  0.000  0.373