In [12]:
from nltk import ngrams
sentence = "The weather is warm and sunny today so we went out today. But tomorrow it will rain"
n = 3
unigrams = ngrams(sentence.split(), n)
for grams in unigrams:
  print (grams)


('The', 'weather', 'is')
('weather', 'is', 'warm')
('is', 'warm', 'and')
('warm', 'and', 'sunny')
('and', 'sunny', 'today')
('sunny', 'today', 'so')
('today', 'so', 'we')
('so', 'we', 'went')
('we', 'went', 'out')
('went', 'out', 'today.')
('out', 'today.', 'But')
('today.', 'But', 'tomorrow')
('But', 'tomorrow', 'it')
('tomorrow', 'it', 'will')
('it', 'will', 'rain')


In [47]:
# prompt: generate proability distribution for next word prediction for ngram of 3

from nltk import ngrams
from collections import defaultdict

sentence = "My address is Tuwaiq Academy.The weather is warm and sunny today so we went out today. But tomorrow it will rain. The weather is colder day after. The weather is so good. The weather is colder before"
n = 3

ngram_counts = defaultdict(lambda: defaultdict(lambda: 0))
total_counts = defaultdict(lambda: 0)

words = sentence.split()
for i in range(len(words) - n + 1):
  ngram = tuple(words[i:i+n-1])
  next_word = words[i+n-1]
  ngram_counts[ngram][next_word] += 1
  total_counts[ngram] += 1

prob_dist = defaultdict(lambda: {})
for ngram, next_word_counts in ngram_counts.items():
  for next_word, count in next_word_counts.items():
    prob_dist[ngram][next_word] = count / total_counts[ngram]

prob_dist.keys().mapping


mappingproxy({('My', 'address'): {'is': 1.0},
              ('address', 'is'): {'Tuwaiq': 1.0},
              ('is', 'Tuwaiq'): {'Academy.The': 1.0},
              ('Tuwaiq', 'Academy.The'): {'weather': 1.0},
              ('Academy.The', 'weather'): {'is': 1.0},
              ('weather', 'is'): {'warm': 0.25, 'colder': 0.5, 'so': 0.25},
              ('is', 'warm'): {'and': 1.0},
              ('warm', 'and'): {'sunny': 1.0},
              ('and', 'sunny'): {'today': 1.0},
              ('sunny', 'today'): {'so': 1.0},
              ('today', 'so'): {'we': 1.0},
              ('so', 'we'): {'went': 1.0},
              ('we', 'went'): {'out': 1.0},
              ('went', 'out'): {'today.': 1.0},
              ('out', 'today.'): {'But': 1.0},
              ('today.', 'But'): {'tomorrow': 1.0},
              ('But', 'tomorrow'): {'it': 1.0},
              ('tomorrow', 'it'): {'will': 1.0},
              ('it', 'will'): {'rain.': 1.0},
              ('will', 'rain.'): {'The': 1.0},
      

In [48]:


from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

corpus = [
 'This is the first, document.',
 'This document is the second document.',
 'And this is the third one.',
 'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X.toarray())


['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [49]:
X = vectorizer.fit_transform(corpus)
pd.DataFrame(X.A, columns=vectorizer.get_feature_names_out())


and  document  first  is  one  second  the  third  this
0    0         1      1   1    0       0    1      0     1
1    0         2      0   1    0       1    1      0     1
2    1         0      0   1    1       0    1      1     1
3    0         1      1   1    0       0    1      0     1

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
"Tune a hyperparameter.",
"You can tune a piano but you can't tune a fish.",
           "Fish who eat fish, catch fish.",
"People can tune a fish or a hyperparameter.",
           "It is hard to catch fish and tune it.",]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(np.round(X.A,3),columns=vectorizer.get_feature_names_out())
df


catch    eat   fish   hard  hyperparameter  people  piano   tune
0  0.000  0.000  0.000  0.000           0.820   0.000  0.000  0.573
1  0.000  0.000  0.350  0.000           0.000   0.000  0.622  0.701
2  0.380  0.471  0.796  0.000           0.000   0.000  0.000  0.000
3  0.000  0.000  0.373  0.000           0.534   0.661  0.000  0.373
4  0.534  0.000  0.373  0.661           0.000   0.000  0.000  0.373

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
"Tune a hyperparameter.",
"You can tune a piano but you can't tune a fish. im adding hyperparameter",
           "Fish who eat fish, catch fish. hyperparameter added",
"People can tune a fish or a hyperparameter.",
           "It is hard to catch fish and tune it. pluse hyperparameter",]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(np.round(X.A,3),columns=vectorizer.get_feature_names_out())
df


added  adding  catch    eat   fish   hard  hyperparameter     im  people  \
0  0.000   0.000  0.000  0.000  0.000  0.000           0.646  0.000   0.000   
1  0.000   0.456  0.000  0.000  0.257  0.000           0.217  0.456   0.000   
2  0.418   0.000  0.337  0.418  0.706  0.000           0.199  0.000   0.000   
3  0.000   0.000  0.000  0.000  0.413  0.000           0.349  0.000   0.733   
4  0.000   0.000  0.430  0.000  0.301  0.534           0.254  0.000   0.000   

   piano  pluse   tune  
0  0.000  0.000  0.764  
1  0.456  0.000  0.514  
2  0.000  0.000  0.000  
3  0.000  0.000  0.413  
4  0.000  0.534  0.301

In [52]:
import nltk

In [55]:
# Suppose we have a paragraph of text related to Saudi Vision 2030
# We tokenize the paragraph into sentences and store them in a list called 'sentences'
paragraph = "Saudi Vision 2030 is a strategic framework aimed at reducing Saudi Arabia's dependence on oil, \
diversifying its economy and developing public service sectors. It encompasses various initiatives \
to achieve long-term goals such as promoting tourism, enhancing eduwomenion, and fostering innovation."
sentences = nltk.sent_tokenize(paragraph)
# Tokenize each sentence into words and store them in a list of lists called 'tokenized_sentences'
tokenized_sentences = [nltk.word_tokenize(sentence) for sentence in sentences]


In [57]:
import gensim

In [58]:
gensim.__version__

'4.3.3'

In [61]:
# We train a Word2Vec model on the 'sentences' data
# The model has parameters like embedding size of 100, window size of 5, and is trained for 10 iterations
from gensim.models import Word2Vec
# Create CBOW model
w2v_CBOW = Word2Vec(tokenized_sentences, vector_size= 20, min_count=1, window=5,)
# Create Skip Gram model
w2v_SG = Word2Vec(tokenized_sentences, min_count=1, vector_size=20, window=5, sg=1)

In [63]:
w2v_SG.alpha

0.025